import { SalesSource, SourceCategory } from '../entities';

export interface SeedSource {
  slug: string;
  name: string;
  category: SourceCategory;
  salesSource: SalesSource;
  host: string | null;
  handle: string | null;
  url: string | null;
  language: string;
  searchUrlTemplate?: string | null;
  feedUrl?: string | null;
}

// Curated registry of trusted sales-information sources. Figures are only
// trusted when they come from one of these; each declares the sales tier it
// maps to.
export const TRUSTED_SOURCES: SeedSource[] = [
  // --- Official investor relations / publisher channels (OFFICIAL) ---
  {
    slug: 'nintendo-ir',
    name: 'Nintendo Investor Relations',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'nintendo.co.jp',
    handle: null,
    url: 'https://www.nintendo.co.jp/ir/en/',
    language: 'en',
  },
  {
    slug: 'sony-ir',
    name: 'Sony Group Investor Relations',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'sony.com',
    handle: null,
    url: 'https://www.sony.com/en/SonyInfo/IR/',
    language: 'en',
  },
  {
    slug: 'microsoft-ir',
    name: 'Microsoft Investor Relations',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'microsoft.com',
    handle: null,
    url: 'https://www.microsoft.com/en-us/investor',
    language: 'en',
  },
  {
    slug: 'take-two-ir',
    name: 'Take-Two Interactive IR',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'take2games.com',
    handle: null,
    url: 'https://ir.take2games.com/',
    language: 'en',
  },
  {
    slug: 'ea-ir',
    name: 'Electronic Arts IR',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'ea.com',
    handle: null,
    url: 'https://ir.ea.com/',
    language: 'en',
  },
  {
    slug: 'ubisoft-ir',
    name: 'Ubisoft Investor Relations',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'ubisoft.com',
    handle: null,
    url: 'https://www.ubisoft.com/en-us/company/investors',
    language: 'en',
  },
  {
    slug: 'cdprojekt-ir',
    name: 'CD Projekt Investor Relations',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'cdprojekt.com',
    handle: null,
    url: 'https://www.cdprojekt.com/en/investors/',
    language: 'en',
  },
  {
    slug: 'playstation-blog',
    name: 'PlayStation Blog',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.ANNOUNCEMENT,
    host: 'blog.playstation.com',
    handle: null,
    url: 'https://blog.playstation.com/',
    language: 'en',
  },
  {
    slug: 'capcom',
    name: 'Capcom',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'capcom.co.jp',
    handle: null,
    url: 'https://www.capcom.co.jp/',
    language: 'en',
  },
  {
    slug: 'sega-sammy',
    name: 'Sega Sammy',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'segasammy.co.jp',
    handle: null,
    url: 'https://www.segasammy.co.jp/',
    language: 'en',
  },
  {
    slug: 'sega',
    name: 'Sega',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'sega.co.jp',
    handle: null,
    url: 'https://www.sega.co.jp/',
    language: 'en',
  },
  {
    slug: 'square-enix',
    name: 'Square Enix',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'square-enix.com',
    handle: null,
    url: 'https://www.square-enix.com/',
    language: 'en',
  },
  {
    slug: 'square-enix-press-na',
    name: 'Square Enix Press (NA)',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'press.na.square-enix.com',
    handle: null,
    url: 'https://press.na.square-enix.com/',
    language: 'en',
  },
  {
    slug: 'square-enix-games',
    name: 'Square Enix Games',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'square-enix-games.com',
    handle: null,
    url: 'https://www.square-enix-games.com/',
    language: 'en',
  },
  {
    slug: 'konami',
    name: 'Konami',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'konami.com',
    handle: null,
    url: 'https://www.konami.com/',
    language: 'en',
  },
  {
    slug: 'focus-entertainment',
    name: 'Focus Entertainment',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'focus-entmt.com',
    handle: null,
    url: 'https://www.focus-entmt.com/',
    language: 'en',
  },
  {
    slug: 'fromsoftware',
    name: 'FromSoftware',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'fromsoftware.jp',
    handle: null,
    url: 'https://www.fromsoftware.jp/',
    language: 'en',
  },
  {
    slug: 'bandai-namco',
    name: 'Bandai Namco',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'bandainamcoent.com',
    handle: null,
    url: 'https://www.bandainamcoent.com/',
    language: 'en',
  },
  {
    slug: 'paradox-interactive',
    name: 'Paradox Interactive',
    category: SourceCategory.OFFICIAL_IR,
    salesSource: SalesSource.OFFICIAL,
    host: 'paradoxinteractive.com',
    handle: null,
    url: 'https://www.paradoxinteractive.com/',
    language: 'en',
  },

  // --- Market analysts (MEDIA tier) ---
  {
    slug: 'circana',
    name: 'Circana (ex-NPD)',
    category: SourceCategory.ANALYST,
    salesSource: SalesSource.MEDIA,
    host: 'circana.com',
    handle: null,
    url: 'https://www.circana.com/',
    language: 'en',
  },
  {
    slug: 'niko-partners',
    name: 'Niko Partners',
    category: SourceCategory.ANALYST,
    salesSource: SalesSource.MEDIA,
    host: 'nikopartners.com',
    handle: null,
    url: 'https://nikopartners.com/',
    language: 'en',
  },
  {
    slug: 'gamediscoverco',
    name: 'GameDiscoverCo',
    category: SourceCategory.ANALYST,
    salesSource: SalesSource.MEDIA,
    host: 'gamediscover.co',
    handle: null,
    url: 'https://newsletter.gamediscover.co/',
    language: 'en',
  },
  {
    slug: 'ampere-analysis',
    name: 'Ampere Analysis',
    category: SourceCategory.ANALYST,
    salesSource: SalesSource.MEDIA,
    host: 'ampereanalysis.com',
    handle: null,
    url: 'https://www.ampereanalysis.com/',
    language: 'en',
  },
  {
    slug: 'alinea-analytics',
    name: 'Alinea Analytics',
    category: SourceCategory.ANALYST,
    salesSource: SalesSource.MEDIA,
    host: 'alineaanalytics.com',
    handle: null,
    url: 'https://alineaanalytics.com/',
    language: 'en',
  },
  {
    slug: 'alinea-analytics-substack',
    name: 'Alinea Analytics (Substack)',
    category: SourceCategory.ANALYST,
    salesSource: SalesSource.MEDIA,
    host: 'alineaanalytics.substack.com',
    handle: null,
    url: 'https://alineaanalytics.substack.com/',
    language: 'en',
  },

  {
    slug: 'wikipedia-en',
    name: 'Wikipedia',
    category: SourceCategory.MEDIA,
    salesSource: SalesSource.WIKIPEDIA,
    host: 'en.wikipedia.org',
    handle: null,
    url: 'https://en.wikipedia.org/',
    language: 'en',
  },

  // --- Press / editorial outlets (MEDIA tier) ---
  {
    slug: 'gamesindustry-biz',
    name: 'GamesIndustry.biz',
    category: SourceCategory.MEDIA,
    salesSource: SalesSource.MEDIA,
    host: 'gamesindustry.biz',
    handle: null,
    url: 'https://www.gamesindustry.biz/',
    language: 'en',
    searchUrlTemplate: 'https://www.gamesindustry.biz/search?q={q}',
    feedUrl: 'https://www.gamesindustry.biz/feed',
  },
  {
    slug: 'vgc',
    name: 'Video Games Chronicle',
    category: SourceCategory.MEDIA,
    salesSource: SalesSource.MEDIA,
    host: 'videogameschronicle.com',
    handle: null,
    url: 'https://www.videogameschronicle.com/',
    language: 'en',
    searchUrlTemplate: 'https://www.videogameschronicle.com/?s={q}',
    feedUrl: 'https://www.videogameschronicle.com/feed/',
  },
  {
    slug: 'eurogamer',
    name: 'Eurogamer',
    category: SourceCategory.MEDIA,
    salesSource: SalesSource.MEDIA,
    host: 'eurogamer.net',
    handle: null,
    url: 'https://www.eurogamer.net/',
    language: 'en',
    searchUrlTemplate: 'https://www.eurogamer.net/search?q={q}',
    feedUrl: 'https://www.eurogamer.net/feed',
  },
  {
    slug: 'pc-gamer',
    name: 'PC Gamer',
    category: SourceCategory.MEDIA,
    salesSource: SalesSource.MEDIA,
    host: 'pcgamer.com',
    handle: null,
    url: 'https://www.pcgamer.com/',
    language: 'en',
    searchUrlTemplate: 'https://www.pcgamer.com/search/?searchTerm={q}',
    feedUrl: 'https://www.pcgamer.com/rss/',
  },
  {
    slug: 'famitsu',
    name: 'Famitsu',
    category: SourceCategory.MEDIA,
    salesSource: SalesSource.MEDIA,
    host: 'famitsu.com',
    handle: null,
    url: 'https://www.famitsu.com/',
    language: 'ja',
  },
  {
    slug: 'ign',
    name: 'IGN',
    category: SourceCategory.MEDIA,
    salesSource: SalesSource.MEDIA,
    host: 'ign.com',
    handle: null,
    url: 'https://www.ign.com/',
    language: 'en',
    feedUrl: 'https://feeds.feedburner.com/ign/all',
  },
  {
    slug: 'push-square',
    name: 'Push Square',
    category: SourceCategory.MEDIA,
    salesSource: SalesSource.MEDIA,
    host: 'pushsquare.com',
    handle: null,
    url: 'https://www.pushsquare.com/',
    language: 'en',
    searchUrlTemplate: 'https://www.pushsquare.com/search?q={q}',
    feedUrl: 'https://www.pushsquare.com/feeds/latest',
  },
];
